### ISSUE TITLE
Las peticiones no se atienden de forma paralela en la generación de entrevistas

### ISSUE THREAD

**Issue by mancuellofran** [EntrevistadorInteligente/preparador-entrevista#7]
Las peticiones no se atienden de forma paralela en la generación de entrevistas. (en los listeners de Kafka solo atiende de 2 en dos) solo soporta 10 peticiones concurrentes. Las demás se pierden.

**Comment by JamiltonQuintero** [comment]
Cerrado con el issue #9  70043984
https://github.com/EntrevistadorInteligente/preparador-entrevista/pull/11
